### PR TITLE
89 exit all taskmanager gracefully

### LINKED ISSUE #86: Exceptions thrown in TaskManager not catched

### LINKED ISSUE #89: Exit all TaskManager gracefully

### PR DESCRIPTION
**Pull request by hferraud**

### CODE REVIEW

File: include/server/TaskManager.hpp [hunk 1]
```diff
@@ -12,10 +12,15 @@
 
 class TaskManager {
 public:
-  explicit TaskManager(ProcessPool &process_pool, PollFds &poll_fds,
-                       int wake_up_fd);
+  TaskManager(ProcessPool &process_pool, PollFds &poll_fds);
```
Comment (EthanDelage) [inline include/server/TaskManager.hpp]: Why are you removing the explicit keyword ?

**Review by EthanDelage — CHANGES_REQUESTED** [review]

File: include/server/TaskManager.hpp (hunk 1 above)
Comment (hferraud) [reply include/server/TaskManager.hpp]: Done f537d09

**Review by EthanDelage — APPROVED** [review]
